apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-landing-zone-ingress
  namespace: {{ .Values.namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- if and .Values.useLetsEncrypt .Values.domain }}
    cert-manager.io/cluster-issuer: "letsencrypt"
    {{- end }}
spec:
  ingressClassName: "public"
  {{- if and .Values.useLetsEncrypt .Values.domain }}
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ printf "%s-tls" (replace "." "-" .Values.domain) }}
  {{- end }}
  defaultBackend:
    service:
      name: default-landing-zone
      port:
        number: 80
