##service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

#### HOW TO CONNECT ##
#  redis.{{ .Release.Name }}.svc.cluster.local:6379
