{{- if not .Values.useHostStorage }}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mariadb-data"
  namespace: {{ .Release.Name | quote }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes:
    - "ReadWriteOncePod"
  resources:
    requests:
      storage: {{ required "persistence.size is required" .Values.persistence.size | quote }}
{{- end }}
