#base image
image: redis:7.0
#host storage path
hostNode: "k8s-master"
hostPort: 6379
# Container data storage
# Existing host files are not copied automatically.
persistence:
  storageClassName: "longhorn"
  size: "2Gi"
